// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_snapshot_by_sandbox_id.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getSnapshotBySandboxID = `-- name: GetSnapshotBySandboxID :one
SELECT s.env_id, s.team_id, eba.build_id
FROM "public"."snapshots" s
LEFT JOIN "public"."env_build_assignments" eba ON eba.env_id = s.env_id AND eba.tag = 'default'
WHERE s.sandbox_id = $1
  AND s.deleted_at IS NULL
ORDER BY eba.created_at DESC
LIMIT 1
`

type GetSnapshotBySandboxIDRow struct {
	EnvID   string
	TeamID  uuid.UUID
	BuildID *uuid.UUID
}

// Returns the live (not soft-deleted) snapshot row for a sandbox together with
// the build assigned to its internal restore template under the 'default' tag.
func (q *Queries) GetSnapshotBySandboxID(ctx context.Context, sandboxID string) (GetSnapshotBySandboxIDRow, error) {
	row := q.db.QueryRow(ctx, getSnapshotBySandboxID, sandboxID)
	var i GetSnapshotBySandboxIDRow
	err := row.Scan(&i.EnvID, &i.TeamID, &i.BuildID)
	return i, err
}
