// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_snapshot_template_with_ready_build.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSnapshotTemplateWithReadyBuild = `-- name: GetSnapshotTemplateWithReadyBuild :one
SELECT st.sandbox_id, st.created_at, eb.id, eb.created_at, eb.updated_at, eb.finished_at, eb.status, eb.dockerfile, eb.start_cmd, eb.vcpu, eb.ram_mb, eb.free_disk_size_mb, eb.total_disk_size_mb, eb.kernel_version, eb.firecracker_version, eb.env_id, eb.envd_version, eb.ready_cmd, eb.cluster_node_id, eb.reason, eb.version, eb.cpu_architecture, eb.cpu_family, eb.cpu_model, eb.cpu_model_name, eb.cpu_flags, eb.status_group, eb.team_id
FROM "public"."snapshot_templates" st
JOIN "public"."envs" e ON e.id = st.env_id AND e.deleted_at IS NULL
JOIN "public"."env_build_assignments" eba ON eba.env_id = e.id AND eba.tag = $1
JOIN "public"."env_builds" eb ON eb.id = eba.build_id AND eb.status_group = 'ready'
WHERE st.env_id = $2
ORDER BY eba.created_at DESC
LIMIT 1
`

type GetSnapshotTemplateWithReadyBuildParams struct {
	Tag        string
	TemplateID string
}

type GetSnapshotTemplateWithReadyBuildRow struct {
	SandboxID string
	CreatedAt pgtype.Timestamptz
	EnvBuild  EnvBuild
}

// Fetches a snapshot (checkpoint) template with its ready build by template ID and tag.
// Checkpoint templates have no snapshots row and no recorded base env, so unlike
// GetLastSnapshot no base-env aliases are returned.
func (q *Queries) GetSnapshotTemplateWithReadyBuild(ctx context.Context, arg GetSnapshotTemplateWithReadyBuildParams) (GetSnapshotTemplateWithReadyBuildRow, error) {
	row := q.db.QueryRow(ctx, getSnapshotTemplateWithReadyBuild, arg.Tag, arg.TemplateID)
	var i GetSnapshotTemplateWithReadyBuildRow
	err := row.Scan(
		&i.SandboxID,
		&i.CreatedAt,
		&i.EnvBuild.ID,
		&i.EnvBuild.CreatedAt,
		&i.EnvBuild.UpdatedAt,
		&i.EnvBuild.FinishedAt,
		&i.EnvBuild.Status,
		&i.EnvBuild.Dockerfile,
		&i.EnvBuild.StartCmd,
		&i.EnvBuild.Vcpu,
		&i.EnvBuild.RamMb,
		&i.EnvBuild.FreeDiskSizeMb,
		&i.EnvBuild.TotalDiskSizeMb,
		&i.EnvBuild.KernelVersion,
		&i.EnvBuild.FirecrackerVersion,
		&i.EnvBuild.EnvID,
		&i.EnvBuild.EnvdVersion,
		&i.EnvBuild.ReadyCmd,
		&i.EnvBuild.ClusterNodeID,
		&i.EnvBuild.Reason,
		&i.EnvBuild.Version,
		&i.EnvBuild.CpuArchitecture,
		&i.EnvBuild.CpuFamily,
		&i.EnvBuild.CpuModel,
		&i.EnvBuild.CpuModelName,
		&i.EnvBuild.CpuFlags,
		&i.EnvBuild.StatusGroup,
		&i.EnvBuild.TeamID,
	)
	return i, err
}
