// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_latest_template_build_status_by_tag.sql

package queries

import (
	"context"

	"github.com/e2b-dev/infra/packages/db/pkg/types"
	"github.com/google/uuid"
)

const getLatestTemplateBuildStatusByTag = `-- name: GetLatestTemplateBuildStatusByTag :one
SELECT eb.id, eb.status, eb.status_group
FROM "public"."env_build_assignments" eba
JOIN "public"."env_builds" eb ON eb.id = eba.build_id
WHERE eba.env_id = $1
  AND eba.tag = $2
ORDER BY eba.created_at DESC
LIMIT 1
`

type GetLatestTemplateBuildStatusByTagParams struct {
	EnvID string
	Tag   string
}

type GetLatestTemplateBuildStatusByTagRow struct {
	ID          uuid.UUID
	Status      types.BuildStatus
	StatusGroup types.BuildStatusGroup
}

// Returns the status of the most recent build assigned to a template under the
// given tag, without status_group filtering. Used to detect in-progress
// snapshotting builds before template deletion.
func (q *Queries) GetLatestTemplateBuildStatusByTag(ctx context.Context, arg GetLatestTemplateBuildStatusByTagParams) (GetLatestTemplateBuildStatusByTagRow, error) {
	row := q.db.QueryRow(ctx, getLatestTemplateBuildStatusByTag, arg.EnvID, arg.Tag)
	var i GetLatestTemplateBuildStatusByTagRow
	err := row.Scan(&i.ID, &i.Status, &i.StatusGroup)
	return i, err
}
