// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_template_including_soft_deleted.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTemplateIncludingSoftDeleted = `-- name: GetTemplateIncludingSoftDeleted :one
SELECT t.id, t.team_id, t.deleted_at
FROM "public"."envs" t
WHERE t.id = $1
`

type GetTemplateIncludingSoftDeletedRow struct {
	ID        string
	TeamID    uuid.UUID
	DeletedAt *time.Time
}

// Returns minimal env info regardless of source or soft-delete state.
// Used by internal delete endpoints to keep repeat deletes idempotent.
func (q *Queries) GetTemplateIncludingSoftDeleted(ctx context.Context, id string) (GetTemplateIncludingSoftDeletedRow, error) {
	row := q.db.QueryRow(ctx, getTemplateIncludingSoftDeleted, id)
	var i GetTemplateIncludingSoftDeletedRow
	err := row.Scan(&i.ID, &i.TeamID, &i.DeletedAt)
	return i, err
}
