// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_env_build_status.sql

package queries

import (
	"context"

	"github.com/e2b-dev/infra/packages/db/pkg/types"
	"github.com/google/uuid"
)

const getEnvBuildStatusByID = `-- name: GetEnvBuildStatusByID :one
SELECT eb.id, eb.status, eb.status_group
FROM "public"."env_builds" eb
WHERE eb.id = $1
`

type GetEnvBuildStatusByIDRow struct {
	ID          uuid.UUID
	Status      types.BuildStatus
	StatusGroup types.BuildStatusGroup
}

// Returns the current status of a build by ID, regardless of the owning env's
// source (template, snapshot, snapshot_template). Used by the internal build
// status write-back endpoint for idempotency/conflict checks.
func (q *Queries) GetEnvBuildStatusByID(ctx context.Context, id uuid.UUID) (GetEnvBuildStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, getEnvBuildStatusByID, id)
	var i GetEnvBuildStatusByIDRow
	err := row.Scan(&i.ID, &i.Status, &i.StatusGroup)
	return i, err
}
