// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: soft_delete_snapshot_by_sandbox_id.sql

package queries

import (
	"context"
)

const softDeleteSnapshotBySandboxID = `-- name: SoftDeleteSnapshotBySandboxID :one
UPDATE "public"."snapshots"
SET deleted_at = now()
WHERE sandbox_id = $1
  AND deleted_at IS NULL
RETURNING env_id
`

// Soft-deletes the snapshot belonging to a sandbox.
// Returns no row when there is no live snapshot for the sandbox
// (caller maps sqlc's no-rows error to 404).
func (q *Queries) SoftDeleteSnapshotBySandboxID(ctx context.Context, sandboxID string) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteSnapshotBySandboxID, sandboxID)
	var env_id string
	err := row.Scan(&env_id)
	return env_id, err
}
