// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: soft_delete_template.sql

package queries

import (
	"context"
)

const softDeleteTemplate = `-- name: SoftDeleteTemplate :many
WITH soft_deleted AS (
  UPDATE "public"."envs" AS e
  SET deleted_at = now()
  WHERE e.id = $1
    AND e.deleted_at IS NULL
  RETURNING e.id
), deleted_aliases AS (
  DELETE FROM "public"."env_aliases" AS ea
  WHERE ea.env_id IN (SELECT id FROM soft_deleted)
  RETURNING CASE
    WHEN namespace IS NOT NULL THEN namespace || '/' || alias
    ELSE alias
  END::text AS alias_key
)
SELECT alias_key FROM deleted_aliases
`

// Soft-deletes a template and deletes its aliases, returning the deleted alias
// cache keys for cache invalidation.
// Idempotent: calling it on an already soft-deleted template returns an empty list.
func (q *Queries) SoftDeleteTemplate(ctx context.Context, templateID string) ([]string, error) {
	rows, err := q.db.Query(ctx, softDeleteTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias_key string
		if err := rows.Scan(&alias_key); err != nil {
			return nil, err
		}
		items = append(items, alias_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
