name: Unit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  unit-tests:
    name: ${{ matrix.package }}
    runs-on: euleros-2.10.1
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: packages/api
            test_path: ./...
          - package: packages/client-proxy
            test_path: ./...
          - package: packages/db
            test_path: ./...
          - package: packages/docker-reverse-proxy
            test_path: ./...
          - package: packages/shared
            test_path: ./pkg/...
          - package: packages/auth
            test_path: ./...
          - package: packages/clickhouse
            test_path: ./...
          - package: packages/local-dev
            test_path: ./...
    steps:
      - uses: checkout-action@0.0.1

      - name: Setup Go
        uses: setup-go@0.0.1
        with:
          go-version: "1.25.4"

      - name: Run unit tests
        run: cd repo_workspace/${{ matrix.package }} && go test -v -race -count=1 -timeout 10m ${{ matrix.test_path }}
