# Code generated by protoc-gen-connect-python 0.1.0.dev2, DO NOT EDIT.
from typing import Any, Generator, Coroutine, AsyncGenerator, Optional
from httpcore import ConnectionPool, AsyncConnectionPool

import e2b_connect as connect

from e2b.checkpointd.checkpoint import checkpoint_pb2 as checkpoint_dot_checkpoint__pb2

CheckpointName = "checkpoint.Checkpoint"


class CheckpointClient:
    def __init__(self, base_url: str, *, pool: Optional[ConnectionPool] = None, async_pool: Optional[AsyncConnectionPool] = None, compressor=None, json=False, **opts):
        self._create_checkpoint = connect.Client(
            pool=pool,
            async_pool=async_pool,
            url=f"{base_url}/{CheckpointName}/CreateCheckpoint",
            response_type=checkpoint_dot_checkpoint__pb2.CreateCheckpointResponse,
            compressor=compressor,
            json=json,
            **opts
        )
        self._restore_checkpoint = connect.Client(
            pool=pool,
            async_pool=async_pool,
            url=f"{base_url}/{CheckpointName}/RestoreCheckpoint",
            response_type=checkpoint_dot_checkpoint__pb2.RestoreCheckpointResponse,
            compressor=compressor,
            json=json,
            **opts
        )
        self._list_checkpoints = connect.Client(
            pool=pool,
            async_pool=async_pool,
            url=f"{base_url}/{CheckpointName}/ListCheckpoints",
            response_type=checkpoint_dot_checkpoint__pb2.ListCheckpointsResponse,
            compressor=compressor,
            json=json,
            **opts
        )
        self._delete_checkpoint = connect.Client(
            pool=pool,
            async_pool=async_pool,
            url=f"{base_url}/{CheckpointName}/DeleteCheckpoint",
            response_type=checkpoint_dot_checkpoint__pb2.DeleteCheckpointResponse,
            compressor=compressor,
            json=json,
            **opts
        )

    def create_checkpoint(self, req: checkpoint_dot_checkpoint__pb2.CreateCheckpointRequest, **opts) -> checkpoint_dot_checkpoint__pb2.CreateCheckpointResponse:
        return self._create_checkpoint.call_unary(req, **opts)

    def acreate_checkpoint(self, req: checkpoint_dot_checkpoint__pb2.CreateCheckpointRequest, **opts) -> Coroutine[Any, Any, checkpoint_dot_checkpoint__pb2.CreateCheckpointResponse]:
        return self._create_checkpoint.acall_unary(req, **opts)

    def restore_checkpoint(self, req: checkpoint_dot_checkpoint__pb2.RestoreCheckpointRequest, **opts) -> checkpoint_dot_checkpoint__pb2.RestoreCheckpointResponse:
        return self._restore_checkpoint.call_unary(req, **opts)

    def arestore_checkpoint(self, req: checkpoint_dot_checkpoint__pb2.RestoreCheckpointRequest, **opts) -> Coroutine[Any, Any, checkpoint_dot_checkpoint__pb2.RestoreCheckpointResponse]:
        return self._restore_checkpoint.acall_unary(req, **opts)

    def list_checkpoints(self, req: checkpoint_dot_checkpoint__pb2.ListCheckpointsRequest, **opts) -> checkpoint_dot_checkpoint__pb2.ListCheckpointsResponse:
        return self._list_checkpoints.call_unary(req, **opts)

    def alist_checkpoints(self, req: checkpoint_dot_checkpoint__pb2.ListCheckpointsRequest, **opts) -> Coroutine[Any, Any, checkpoint_dot_checkpoint__pb2.ListCheckpointsResponse]:
        return self._list_checkpoints.acall_unary(req, **opts)

    def delete_checkpoint(self, req: checkpoint_dot_checkpoint__pb2.DeleteCheckpointRequest, **opts) -> checkpoint_dot_checkpoint__pb2.DeleteCheckpointResponse:
        return self._delete_checkpoint.call_unary(req, **opts)

    def adelete_checkpoint(self, req: checkpoint_dot_checkpoint__pb2.DeleteCheckpointRequest, **opts) -> Coroutine[Any, Any, checkpoint_dot_checkpoint__pb2.DeleteCheckpointResponse]:
        return self._delete_checkpoint.acall_unary(req, **opts)
