# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkpoint/checkpoint.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bcheckpoint/checkpoint.proto\x12\ncheckpoint";\n\x17CreateCheckpointRequest\x12\x17\n\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\x07\n\x05_name"Z\n\x18CreateCheckpointResponse\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0ccheckpointId\x12\x19\n\x08mem_mode\x18\x02 \x01(\tR\x07memMode"?\n\x18RestoreCheckpointRequest\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0ccheckpointId"5\n\x19RestoreCheckpointResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success"\x18\n\x16ListCheckpointsRequest"W\n\x17ListCheckpointsResponse\x12<\n\x0bcheckpoints\x18\x01 \x03(\x0b2\x1a.checkpoint.CheckpointInfoR\x0bcheckpoints">\n\x17DeleteCheckpointRequest\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0ccheckpointId"4\n\x18DeleteCheckpointResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success"\x91\x01\n\x0eCheckpointInfo\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0ccheckpointId\x12\x17\n\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n\ncreated_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x19\n\x08mem_mode\x18\x04 \x01(\tR\x07memModeB\x07\n\x05_name2\x88\x03\n\nCheckpoint\x12]\n\x10CreateCheckpoint\x12#.checkpoint.CreateCheckpointRequest\x1a$.checkpoint.CreateCheckpointResponse\x12`\n\x11RestoreCheckpoint\x12$.checkpoint.RestoreCheckpointRequest\x1a%.checkpoint.RestoreCheckpointResponse\x12Z\n\x0fListCheckpoints\x12".checkpoint.ListCheckpointsRequest\x1a#.checkpoint.ListCheckpointsResponse\x12]\n\x10DeleteCheckpoint\x12#.checkpoint.DeleteCheckpointRequest\x1a$.checkpoint.DeleteCheckpointResponseB\xb2\x01\n\x0ecom.checkpointB\x0fCheckpointProtoP\x01ZGgithub.com/e2b-dev/infra/packages/orchestrator/internal/checkpoint/spec\xa2\x02\x03CXX\xaa\x02\nCheckpoint\xca\x02\nCheckpoint\xe2\x02\x16Checkpoint\\GPBMetadata\xea\x02\nCheckpointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkpoint.checkpoint_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\x0ecom.checkpointB\x0fCheckpointProtoP\x01ZGgithub.com/e2b-dev/infra/packages/orchestrator/internal/checkpoint/spec\xa2\x02\x03CXX\xaa\x02\nCheckpoint\xca\x02\nCheckpoint\xe2\x02\x16Checkpoint\\GPBMetadata\xea\x02\nCheckpoint'
  _globals['_CREATECHECKPOINTREQUEST']._serialized_start=43
  _globals['_CREATECHECKPOINTREQUEST']._serialized_end=102
  _globals['_CREATECHECKPOINTRESPONSE']._serialized_start=104
  _globals['_CREATECHECKPOINTRESPONSE']._serialized_end=194
  _globals['_RESTORECHECKPOINTREQUEST']._serialized_start=196
  _globals['_RESTORECHECKPOINTREQUEST']._serialized_end=259
  _globals['_RESTORECHECKPOINTRESPONSE']._serialized_start=261
  _globals['_RESTORECHECKPOINTRESPONSE']._serialized_end=314
  _globals['_LISTCHECKPOINTSREQUEST']._serialized_start=316
  _globals['_LISTCHECKPOINTSREQUEST']._serialized_end=340
  _globals['_LISTCHECKPOINTSRESPONSE']._serialized_start=342
  _globals['_LISTCHECKPOINTSRESPONSE']._serialized_end=429
  _globals['_DELETECHECKPOINTREQUEST']._serialized_start=431
  _globals['_DELETECHECKPOINTREQUEST']._serialized_end=493
  _globals['_DELETECHECKPOINTRESPONSE']._serialized_start=495
  _globals['_DELETECHECKPOINTRESPONSE']._serialized_end=547
  _globals['_CHECKPOINTINFO']._serialized_start=550
  _globals['_CHECKPOINTINFO']._serialized_end=695
  _globals['_CHECKPOINT']._serialized_start=698
  _globals['_CHECKPOINT']._serialized_end=1090
# @@protoc_insertion_point(module_scope)
