// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	E2BSandboxAdminService_PauseSandbox_FullMethodName      = "/crimultiplex.admin.v1.E2BSandboxAdminService/PauseSandbox"
	E2BSandboxAdminService_CheckpointSandbox_FullMethodName = "/crimultiplex.admin.v1.E2BSandboxAdminService/CheckpointSandbox"
	E2BSandboxAdminService_GetSandboxRuntime_FullMethodName = "/crimultiplex.admin.v1.E2BSandboxAdminService/GetSandboxRuntime"
)

// E2BSandboxAdminServiceClient is the client API for E2BSandboxAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// E2BSandboxAdminService 是节点本地管理面，仅供 Node Agent 通过 unix socket 调用。
type E2BSandboxAdminServiceClient interface {
	// 为指定 E2B sandbox 执行 Pause：拍快照并等待持久化，随后 VM 由 Orchestrator 停止
	PauseSandbox(ctx context.Context, in *PauseSandboxRequest, opts ...grpc.CallOption) (*PauseSandboxResponse, error)
	// 为指定 E2B sandbox 执行 Checkpoint：拍快照、等待持久化、VM 原地恢复继续运行
	CheckpointSandbox(ctx context.Context, in *CheckpointSandboxRequest, opts ...grpc.CallOption) (*CheckpointSandboxResponse, error)
	// 查询节点运行事实（身份、状态、CNI、HostPort、进行中操作）
	GetSandboxRuntime(ctx context.Context, in *GetSandboxRuntimeRequest, opts ...grpc.CallOption) (*GetSandboxRuntimeResponse, error)
}

type e2BSandboxAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewE2BSandboxAdminServiceClient(cc grpc.ClientConnInterface) E2BSandboxAdminServiceClient {
	return &e2BSandboxAdminServiceClient{cc}
}

func (c *e2BSandboxAdminServiceClient) PauseSandbox(ctx context.Context, in *PauseSandboxRequest, opts ...grpc.CallOption) (*PauseSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseSandboxResponse)
	err := c.cc.Invoke(ctx, E2BSandboxAdminService_PauseSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2BSandboxAdminServiceClient) CheckpointSandbox(ctx context.Context, in *CheckpointSandboxRequest, opts ...grpc.CallOption) (*CheckpointSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointSandboxResponse)
	err := c.cc.Invoke(ctx, E2BSandboxAdminService_CheckpointSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2BSandboxAdminServiceClient) GetSandboxRuntime(ctx context.Context, in *GetSandboxRuntimeRequest, opts ...grpc.CallOption) (*GetSandboxRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxRuntimeResponse)
	err := c.cc.Invoke(ctx, E2BSandboxAdminService_GetSandboxRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// E2BSandboxAdminServiceServer is the server API for E2BSandboxAdminService service.
// All implementations must embed UnimplementedE2BSandboxAdminServiceServer
// for forward compatibility.
//
// E2BSandboxAdminService 是节点本地管理面，仅供 Node Agent 通过 unix socket 调用。
type E2BSandboxAdminServiceServer interface {
	// 为指定 E2B sandbox 执行 Pause：拍快照并等待持久化，随后 VM 由 Orchestrator 停止
	PauseSandbox(context.Context, *PauseSandboxRequest) (*PauseSandboxResponse, error)
	// 为指定 E2B sandbox 执行 Checkpoint：拍快照、等待持久化、VM 原地恢复继续运行
	CheckpointSandbox(context.Context, *CheckpointSandboxRequest) (*CheckpointSandboxResponse, error)
	// 查询节点运行事实（身份、状态、CNI、HostPort、进行中操作）
	GetSandboxRuntime(context.Context, *GetSandboxRuntimeRequest) (*GetSandboxRuntimeResponse, error)
	mustEmbedUnimplementedE2BSandboxAdminServiceServer()
}

// UnimplementedE2BSandboxAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedE2BSandboxAdminServiceServer struct{}

func (UnimplementedE2BSandboxAdminServiceServer) PauseSandbox(context.Context, *PauseSandboxRequest) (*PauseSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSandbox not implemented")
}
func (UnimplementedE2BSandboxAdminServiceServer) CheckpointSandbox(context.Context, *CheckpointSandboxRequest) (*CheckpointSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointSandbox not implemented")
}
func (UnimplementedE2BSandboxAdminServiceServer) GetSandboxRuntime(context.Context, *GetSandboxRuntimeRequest) (*GetSandboxRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxRuntime not implemented")
}
func (UnimplementedE2BSandboxAdminServiceServer) mustEmbedUnimplementedE2BSandboxAdminServiceServer() {
}
func (UnimplementedE2BSandboxAdminServiceServer) testEmbeddedByValue() {}

// UnsafeE2BSandboxAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to E2BSandboxAdminServiceServer will
// result in compilation errors.
type UnsafeE2BSandboxAdminServiceServer interface {
	mustEmbedUnimplementedE2BSandboxAdminServiceServer()
}

func RegisterE2BSandboxAdminServiceServer(s grpc.ServiceRegistrar, srv E2BSandboxAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedE2BSandboxAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&E2BSandboxAdminService_ServiceDesc, srv)
}

func _E2BSandboxAdminService_PauseSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2BSandboxAdminServiceServer).PauseSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2BSandboxAdminService_PauseSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2BSandboxAdminServiceServer).PauseSandbox(ctx, req.(*PauseSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2BSandboxAdminService_CheckpointSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2BSandboxAdminServiceServer).CheckpointSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2BSandboxAdminService_CheckpointSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2BSandboxAdminServiceServer).CheckpointSandbox(ctx, req.(*CheckpointSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2BSandboxAdminService_GetSandboxRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2BSandboxAdminServiceServer).GetSandboxRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2BSandboxAdminService_GetSandboxRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2BSandboxAdminServiceServer).GetSandboxRuntime(ctx, req.(*GetSandboxRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// E2BSandboxAdminService_ServiceDesc is the grpc.ServiceDesc for E2BSandboxAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var E2BSandboxAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crimultiplex.admin.v1.E2BSandboxAdminService",
	HandlerType: (*E2BSandboxAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PauseSandbox",
			Handler:    _E2BSandboxAdminService_PauseSandbox_Handler,
		},
		{
			MethodName: "CheckpointSandbox",
			Handler:    _E2BSandboxAdminService_CheckpointSandbox_Handler,
		},
		{
			MethodName: "GetSandboxRuntime",
			Handler:    _E2BSandboxAdminService_GetSandboxRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
