apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-e2b-app
  namespace: e2b   # 请改成 edge-api 所在命名空间
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: "*.e2b.app"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edge-api      # 你的 headless 服务名
            port:
              number: 3002      # 转发到 3002 端口