# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkpoint/checkpoint.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63heckpoint/checkpoint.proto\x12\ncheckpoint\";\n\x17\x43reateCheckpointRequest\x12\x17\n\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x42\x07\n\x05_name\"?\n\x18\x43reateCheckpointResponse\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0c\x63heckpointId\"?\n\x18RestoreCheckpointRequest\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0c\x63heckpointId\"5\n\x19RestoreCheckpointResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"\x18\n\x16ListCheckpointsRequest\"W\n\x17ListCheckpointsResponse\x12<\n\x0b\x63heckpoints\x18\x01 \x03(\x0b\x32\x1a.checkpoint.CheckpointInfoR\x0b\x63heckpoints\">\n\x17\x44\x65leteCheckpointRequest\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0c\x63heckpointId\"4\n\x18\x44\x65leteCheckpointResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"v\n\x0e\x43heckpointInfo\x12#\n\rcheckpoint_id\x18\x01 \x01(\tR\x0c\x63heckpointId\x12\x17\n\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n\ncreated_at\x18\x03 \x01(\x03R\tcreatedAtB\x07\n\x05_name2\x88\x03\n\nCheckpoint\x12]\n\x10\x43reateCheckpoint\x12#.checkpoint.CreateCheckpointRequest\x1a$.checkpoint.CreateCheckpointResponse\x12`\n\x11RestoreCheckpoint\x12$.checkpoint.RestoreCheckpointRequest\x1a%.checkpoint.RestoreCheckpointResponse\x12Z\n\x0fListCheckpoints\x12\".checkpoint.ListCheckpointsRequest\x1a#.checkpoint.ListCheckpointsResponse\x12]\n\x10\x44\x65leteCheckpoint\x12#.checkpoint.DeleteCheckpointRequest\x1a$.checkpoint.DeleteCheckpointResponseB\xb2\x01\n\x0e\x63om.checkpointB\x0f\x43heckpointProtoP\x01ZGgithub.com/e2b-dev/infra/packages/gsd/internal/services/spec/checkpoint\xa2\x02\x03\x43XX\xaa\x02\nCheckpoint\xca\x02\nCheckpoint\xe2\x02\x16\x43heckpoint\\GPBMetadata\xea\x02\nCheckpointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkpoint.checkpoint_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.checkpointB\017CheckpointProtoP\001ZGgithub.com/e2b-dev/infra/packages/gsd/internal/services/spec/checkpoint\242\002\003CXX\252\002\nCheckpoint\312\002\nCheckpoint\342\002\026Checkpoint\\GPBMetadata\352\002\nCheckpoint'
  _globals['_CREATECHECKPOINTREQUEST']._serialized_start=43
  _globals['_CREATECHECKPOINTREQUEST']._serialized_end=102
  _globals['_CREATECHECKPOINTRESPONSE']._serialized_start=104
  _globals['_CREATECHECKPOINTRESPONSE']._serialized_end=167
  _globals['_RESTORECHECKPOINTREQUEST']._serialized_start=169
  _globals['_RESTORECHECKPOINTREQUEST']._serialized_end=232
  _globals['_RESTORECHECKPOINTRESPONSE']._serialized_start=234
  _globals['_RESTORECHECKPOINTRESPONSE']._serialized_end=287
  _globals['_LISTCHECKPOINTSREQUEST']._serialized_start=289
  _globals['_LISTCHECKPOINTSREQUEST']._serialized_end=313
  _globals['_LISTCHECKPOINTSRESPONSE']._serialized_start=315
  _globals['_LISTCHECKPOINTSRESPONSE']._serialized_end=402
  _globals['_DELETECHECKPOINTREQUEST']._serialized_start=404
  _globals['_DELETECHECKPOINTREQUEST']._serialized_end=466
  _globals['_DELETECHECKPOINTRESPONSE']._serialized_start=468
  _globals['_DELETECHECKPOINTRESPONSE']._serialized_end=520
  _globals['_CHECKPOINTINFO']._serialized_start=522
  _globals['_CHECKPOINTINFO']._serialized_end=640
  _globals['_CHECKPOINT']._serialized_start=643
  _globals['_CHECKPOINT']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
