// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: orchestrator.proto

package orchestrator

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data required for creating a new sandbox.
	TemplateId         string            `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId            string            `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	KernelVersion      string            `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	FirecrackerVersion string            `protobuf:"bytes,4,opt,name=firecracker_version,json=firecrackerVersion,proto3" json:"firecracker_version,omitempty"`
	HugePages          bool              `protobuf:"varint,5,opt,name=huge_pages,json=hugePages,proto3" json:"huge_pages,omitempty"`
	SandboxId          string            `protobuf:"bytes,6,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	EnvVars            map[string]string `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata about the sandbox.
	Metadata    map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Alias       *string           `protobuf:"bytes,9,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	EnvdVersion string            `protobuf:"bytes,10,opt,name=envd_version,json=envdVersion,proto3" json:"envd_version,omitempty"`
	Vcpu        int64             `protobuf:"varint,11,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	RamMb       int64             `protobuf:"varint,12,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	TeamId      string            `protobuf:"bytes,13,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Maximum length of the sandbox in Hours.
	MaxSandboxLength int64   `protobuf:"varint,14,opt,name=max_sandbox_length,json=maxSandboxLength,proto3" json:"max_sandbox_length,omitempty"`
	TotalDiskSizeMb  int64   `protobuf:"varint,15,opt,name=total_disk_size_mb,json=totalDiskSizeMb,proto3" json:"total_disk_size_mb,omitempty"`
	Snapshot         bool    `protobuf:"varint,16,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	BaseTemplateId   string  `protobuf:"bytes,17,opt,name=base_template_id,json=baseTemplateId,proto3" json:"base_template_id,omitempty"`
	AutoPause        bool    `protobuf:"varint,18,opt,name=auto_pause,json=autoPause,proto3" json:"auto_pause,omitempty"`
	EnvdAccessToken  *string `protobuf:"bytes,19,opt,name=envd_access_token,json=envdAccessToken,proto3,oneof" json:"envd_access_token,omitempty"`
	ExecutionId      string  `protobuf:"bytes,20,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Whether the sandbox should have access to the internet.
	// This is optional only for backwards compatibility.
	// After migration, the optional keyword can be removed.
	AllowInternetAccess *bool                 `protobuf:"varint,21,opt,name=allow_internet_access,json=allowInternetAccess,proto3,oneof" json:"allow_internet_access,omitempty"`
	Network             *SandboxNetworkConfig `protobuf:"bytes,22,opt,name=network,proto3,oneof" json:"network,omitempty"`
	VolumeMounts        []*SandboxVolumeMount `protobuf:"bytes,23,rep,name=volumeMounts,proto3" json:"volumeMounts,omitempty"`
	// Auto-resume policy for paused sandboxes.
	AutoResume    *SandboxAutoResumeConfig `protobuf:"bytes,24,opt,name=auto_resume,json=autoResume,proto3,oneof" json:"auto_resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxConfig) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxConfig) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxConfig) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SandboxConfig) GetFirecrackerVersion() string {
	if x != nil {
		return x.FirecrackerVersion
	}
	return ""
}

func (x *SandboxConfig) GetHugePages() bool {
	if x != nil {
		return x.HugePages
	}
	return false
}

func (x *SandboxConfig) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxConfig) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SandboxConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxConfig) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *SandboxConfig) GetEnvdVersion() string {
	if x != nil {
		return x.EnvdVersion
	}
	return ""
}

func (x *SandboxConfig) GetVcpu() int64 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *SandboxConfig) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *SandboxConfig) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SandboxConfig) GetMaxSandboxLength() int64 {
	if x != nil {
		return x.MaxSandboxLength
	}
	return 0
}

func (x *SandboxConfig) GetTotalDiskSizeMb() int64 {
	if x != nil {
		return x.TotalDiskSizeMb
	}
	return 0
}

func (x *SandboxConfig) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *SandboxConfig) GetBaseTemplateId() string {
	if x != nil {
		return x.BaseTemplateId
	}
	return ""
}

func (x *SandboxConfig) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *SandboxConfig) GetEnvdAccessToken() string {
	if x != nil && x.EnvdAccessToken != nil {
		return *x.EnvdAccessToken
	}
	return ""
}

func (x *SandboxConfig) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxConfig) GetAllowInternetAccess() bool {
	if x != nil && x.AllowInternetAccess != nil {
		return *x.AllowInternetAccess
	}
	return false
}

func (x *SandboxConfig) GetNetwork() *SandboxNetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SandboxConfig) GetVolumeMounts() []*SandboxVolumeMount {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

func (x *SandboxConfig) GetAutoResume() *SandboxAutoResumeConfig {
	if x != nil {
		return x.AutoResume
	}
	return nil
}

type SandboxAutoResumeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy values are owned by the API layer today (e.g. "off", "any").
	Policy string `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	// Timeout requested on initial sandbox create (seconds).
	TimeoutSeconds uint64 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxAutoResumeConfig) Reset() {
	*x = SandboxAutoResumeConfig{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxAutoResumeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxAutoResumeConfig) ProtoMessage() {}

func (x *SandboxAutoResumeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxAutoResumeConfig.ProtoReflect.Descriptor instead.
func (*SandboxAutoResumeConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxAutoResumeConfig) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *SandboxAutoResumeConfig) GetTimeoutSeconds() uint64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SandboxVolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxVolumeMount) Reset() {
	*x = SandboxVolumeMount{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxVolumeMount) ProtoMessage() {}

func (x *SandboxVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxVolumeMount.ProtoReflect.Descriptor instead.
func (*SandboxVolumeMount) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxVolumeMount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxVolumeMount) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SandboxVolumeMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SandboxVolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SandboxNetworkConfig struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Egress        *SandboxNetworkEgressConfig  `protobuf:"bytes,1,opt,name=egress,proto3,oneof" json:"egress,omitempty"`
	Ingress       *SandboxNetworkIngressConfig `protobuf:"bytes,2,opt,name=ingress,proto3,oneof" json:"ingress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkConfig) Reset() {
	*x = SandboxNetworkConfig{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkConfig) ProtoMessage() {}

func (x *SandboxNetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkConfig.ProtoReflect.Descriptor instead.
func (*SandboxNetworkConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxNetworkConfig) GetEgress() *SandboxNetworkEgressConfig {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *SandboxNetworkConfig) GetIngress() *SandboxNetworkIngressConfig {
	if x != nil {
		return x.Ingress
	}
	return nil
}

type SandboxNetworkTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkTransform) Reset() {
	*x = SandboxNetworkTransform{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkTransform) ProtoMessage() {}

func (x *SandboxNetworkTransform) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkTransform.ProtoReflect.Descriptor instead.
func (*SandboxNetworkTransform) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxNetworkTransform) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type SandboxNetworkRule struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Transform     *SandboxNetworkTransform `protobuf:"bytes,1,opt,name=transform,proto3,oneof" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkRule) Reset() {
	*x = SandboxNetworkRule{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkRule) ProtoMessage() {}

func (x *SandboxNetworkRule) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkRule.ProtoReflect.Descriptor instead.
func (*SandboxNetworkRule) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxNetworkRule) GetTransform() *SandboxNetworkTransform {
	if x != nil {
		return x.Transform
	}
	return nil
}

type SandboxNetworkDomainRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*SandboxNetworkRule  `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkDomainRules) Reset() {
	*x = SandboxNetworkDomainRules{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkDomainRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkDomainRules) ProtoMessage() {}

func (x *SandboxNetworkDomainRules) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkDomainRules.ProtoReflect.Descriptor instead.
func (*SandboxNetworkDomainRules) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxNetworkDomainRules) GetRules() []*SandboxNetworkRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SandboxNetworkEgressConfig struct {
	state          protoimpl.MessageState                `protogen:"open.v1"`
	AllowedCidrs   []string                              `protobuf:"bytes,1,rep,name=allowed_cidrs,json=allowedCidrs,proto3" json:"allowed_cidrs,omitempty"`
	DeniedCidrs    []string                              `protobuf:"bytes,2,rep,name=denied_cidrs,json=deniedCidrs,proto3" json:"denied_cidrs,omitempty"`
	AllowedDomains []string                              `protobuf:"bytes,3,rep,name=allowed_domains,json=allowedDomains,proto3" json:"allowed_domains,omitempty"`
	Rules          map[string]*SandboxNetworkDomainRules `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxNetworkEgressConfig) Reset() {
	*x = SandboxNetworkEgressConfig{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkEgressConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkEgressConfig) ProtoMessage() {}

func (x *SandboxNetworkEgressConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkEgressConfig.ProtoReflect.Descriptor instead.
func (*SandboxNetworkEgressConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *SandboxNetworkEgressConfig) GetAllowedCidrs() []string {
	if x != nil {
		return x.AllowedCidrs
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetDeniedCidrs() []string {
	if x != nil {
		return x.DeniedCidrs
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetAllowedDomains() []string {
	if x != nil {
		return x.AllowedDomains
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetRules() map[string]*SandboxNetworkDomainRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SandboxNetworkIngressConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TrafficAccessToken *string                `protobuf:"bytes,1,opt,name=traffic_access_token,json=trafficAccessToken,proto3,oneof" json:"traffic_access_token,omitempty"`
	MaskRequestHost    *string                `protobuf:"bytes,2,opt,name=mask_request_host,json=maskRequestHost,proto3,oneof" json:"mask_request_host,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxNetworkIngressConfig) Reset() {
	*x = SandboxNetworkIngressConfig{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkIngressConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkIngressConfig) ProtoMessage() {}

func (x *SandboxNetworkIngressConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkIngressConfig.ProtoReflect.Descriptor instead.
func (*SandboxNetworkIngressConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *SandboxNetworkIngressConfig) GetTrafficAccessToken() string {
	if x != nil && x.TrafficAccessToken != nil {
		return *x.TrafficAccessToken
	}
	return ""
}

func (x *SandboxNetworkIngressConfig) GetMaskRequestHost() string {
	if x != nil && x.MaskRequestHost != nil {
		return *x.MaskRequestHost
	}
	return ""
}

type SandboxCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *SandboxConfig         `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	StartTime     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCreateRequest) Reset() {
	*x = SandboxCreateRequest{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateRequest) ProtoMessage() {}

func (x *SandboxCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateRequest.ProtoReflect.Descriptor instead.
func (*SandboxCreateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *SandboxCreateRequest) GetSandbox() *SandboxConfig {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *SandboxCreateRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SandboxCreateRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type SandboxCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCreateResponse) Reset() {
	*x = SandboxCreateResponse{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateResponse) ProtoMessage() {}

func (x *SandboxCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateResponse.ProtoReflect.Descriptor instead.
func (*SandboxCreateResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *SandboxCreateResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SandboxUpdateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// All fields are optional — only set fields are applied.
	EndTime       *timestamp.Timestamp        `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	Egress        *SandboxNetworkEgressConfig `protobuf:"bytes,3,opt,name=egress,proto3,oneof" json:"egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxUpdateRequest) Reset() {
	*x = SandboxUpdateRequest{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxUpdateRequest) ProtoMessage() {}

func (x *SandboxUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxUpdateRequest.ProtoReflect.Descriptor instead.
func (*SandboxUpdateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *SandboxUpdateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxUpdateRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SandboxUpdateRequest) GetEgress() *SandboxNetworkEgressConfig {
	if x != nil {
		return x.Egress
	}
	return nil
}

type SandboxDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxDeleteRequest) Reset() {
	*x = SandboxDeleteRequest{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxDeleteRequest) ProtoMessage() {}

func (x *SandboxDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxDeleteRequest.ProtoReflect.Descriptor instead.
func (*SandboxDeleteRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *SandboxDeleteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type SandboxPauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxPauseRequest) Reset() {
	*x = SandboxPauseRequest{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPauseRequest) ProtoMessage() {}

func (x *SandboxPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPauseRequest.ProtoReflect.Descriptor instead.
func (*SandboxPauseRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxPauseRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxPauseRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxPauseRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type SandboxCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCheckpointRequest) Reset() {
	*x = SandboxCheckpointRequest{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointRequest) ProtoMessage() {}

func (x *SandboxCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *SandboxCheckpointRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxCheckpointRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type SandboxCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCheckpointResponse) Reset() {
	*x = SandboxCheckpointResponse{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointResponse) ProtoMessage() {}

func (x *SandboxCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

type RunningSandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SandboxConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StartTime     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningSandbox) Reset() {
	*x = RunningSandbox{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningSandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningSandbox) ProtoMessage() {}

func (x *RunningSandbox) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningSandbox.ProtoReflect.Descriptor instead.
func (*RunningSandbox) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *RunningSandbox) GetConfig() *SandboxConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RunningSandbox) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RunningSandbox) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RunningSandbox) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type SandboxListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*RunningSandbox      `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxListResponse) Reset() {
	*x = SandboxListResponse{}
	mi := &file_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxListResponse) ProtoMessage() {}

func (x *SandboxListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxListResponse.ProtoReflect.Descriptor instead.
func (*SandboxListResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *SandboxListResponse) GetSandboxes() []*RunningSandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type CachedBuildInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuildId        string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ExpirationTime *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CachedBuildInfo) Reset() {
	*x = CachedBuildInfo{}
	mi := &file_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedBuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedBuildInfo) ProtoMessage() {}

func (x *CachedBuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedBuildInfo.ProtoReflect.Descriptor instead.
func (*CachedBuildInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *CachedBuildInfo) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CachedBuildInfo) GetExpirationTime() *timestamp.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

type SandboxListCachedBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*CachedBuildInfo     `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxListCachedBuildsResponse) Reset() {
	*x = SandboxListCachedBuildsResponse{}
	mi := &file_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxListCachedBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxListCachedBuildsResponse) ProtoMessage() {}

func (x *SandboxListCachedBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxListCachedBuildsResponse.ProtoReflect.Descriptor instead.
func (*SandboxListCachedBuildsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *SandboxListCachedBuildsResponse) GetBuilds() []*CachedBuildInfo {
	if x != nil {
		return x.Builds
	}
	return nil
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\t\n" +
	"\rSandboxConfig\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12/\n" +
	"\x13firecracker_version\x18\x04 \x01(\tR\x12firecrackerVersion\x12\x1d\n" +
	"\n" +
	"huge_pages\x18\x05 \x01(\bR\thugePages\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x06 \x01(\tR\tsandboxId\x126\n" +
	"\benv_vars\x18\a \x03(\v2\x1b.SandboxConfig.EnvVarsEntryR\aenvVars\x128\n" +
	"\bmetadata\x18\b \x03(\v2\x1c.SandboxConfig.MetadataEntryR\bmetadata\x12\x19\n" +
	"\x05alias\x18\t \x01(\tH\x00R\x05alias\x88\x01\x01\x12!\n" +
	"\fenvd_version\x18\n" +
	" \x01(\tR\venvdVersion\x12\x12\n" +
	"\x04vcpu\x18\v \x01(\x03R\x04vcpu\x12\x15\n" +
	"\x06ram_mb\x18\f \x01(\x03R\x05ramMb\x12\x17\n" +
	"\ateam_id\x18\r \x01(\tR\x06teamId\x12,\n" +
	"\x12max_sandbox_length\x18\x0e \x01(\x03R\x10maxSandboxLength\x12+\n" +
	"\x12total_disk_size_mb\x18\x0f \x01(\x03R\x0ftotalDiskSizeMb\x12\x1a\n" +
	"\bsnapshot\x18\x10 \x01(\bR\bsnapshot\x12(\n" +
	"\x10base_template_id\x18\x11 \x01(\tR\x0ebaseTemplateId\x12\x1d\n" +
	"\n" +
	"auto_pause\x18\x12 \x01(\bR\tautoPause\x12/\n" +
	"\x11envd_access_token\x18\x13 \x01(\tH\x01R\x0fenvdAccessToken\x88\x01\x01\x12!\n" +
	"\fexecution_id\x18\x14 \x01(\tR\vexecutionId\x127\n" +
	"\x15allow_internet_access\x18\x15 \x01(\bH\x02R\x13allowInternetAccess\x88\x01\x01\x124\n" +
	"\anetwork\x18\x16 \x01(\v2\x15.SandboxNetworkConfigH\x03R\anetwork\x88\x01\x01\x127\n" +
	"\fvolumeMounts\x18\x17 \x03(\v2\x13.SandboxVolumeMountR\fvolumeMounts\x12>\n" +
	"\vauto_resume\x18\x18 \x01(\v2\x18.SandboxAutoResumeConfigH\x04R\n" +
	"autoResume\x88\x01\x01\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_aliasB\x14\n" +
	"\x12_envd_access_tokenB\x18\n" +
	"\x16_allow_internet_accessB\n" +
	"\n" +
	"\b_networkB\x0e\n" +
	"\f_auto_resume\"Z\n" +
	"\x17SandboxAutoResumeConfig\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x04R\x0etimeoutSeconds\"`\n" +
	"\x12SandboxVolumeMount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa4\x01\n" +
	"\x14SandboxNetworkConfig\x128\n" +
	"\x06egress\x18\x01 \x01(\v2\x1b.SandboxNetworkEgressConfigH\x00R\x06egress\x88\x01\x01\x12;\n" +
	"\aingress\x18\x02 \x01(\v2\x1c.SandboxNetworkIngressConfigH\x01R\aingress\x88\x01\x01B\t\n" +
	"\a_egressB\n" +
	"\n" +
	"\b_ingress\"\x96\x01\n" +
	"\x17SandboxNetworkTransform\x12?\n" +
	"\aheaders\x18\x01 \x03(\v2%.SandboxNetworkTransform.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x12SandboxNetworkRule\x12;\n" +
	"\ttransform\x18\x01 \x01(\v2\x18.SandboxNetworkTransformH\x00R\ttransform\x88\x01\x01B\f\n" +
	"\n" +
	"_transform\"F\n" +
	"\x19SandboxNetworkDomainRules\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.SandboxNetworkRuleR\x05rules\"\xa1\x02\n" +
	"\x1aSandboxNetworkEgressConfig\x12#\n" +
	"\rallowed_cidrs\x18\x01 \x03(\tR\fallowedCidrs\x12!\n" +
	"\fdenied_cidrs\x18\x02 \x03(\tR\vdeniedCidrs\x12'\n" +
	"\x0fallowed_domains\x18\x03 \x03(\tR\x0eallowedDomains\x12<\n" +
	"\x05rules\x18\x04 \x03(\v2&.SandboxNetworkEgressConfig.RulesEntryR\x05rules\x1aT\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.SandboxNetworkDomainRulesR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x1bSandboxNetworkIngressConfig\x125\n" +
	"\x14traffic_access_token\x18\x01 \x01(\tH\x00R\x12trafficAccessToken\x88\x01\x01\x12/\n" +
	"\x11mask_request_host\x18\x02 \x01(\tH\x01R\x0fmaskRequestHost\x88\x01\x01B\x17\n" +
	"\x15_traffic_access_tokenB\x14\n" +
	"\x12_mask_request_host\"\xb2\x01\n" +
	"\x14SandboxCreateRequest\x12(\n" +
	"\asandbox\x18\x01 \x01(\v2\x0e.SandboxConfigR\asandbox\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"4\n" +
	"\x15SandboxCreateResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xc3\x01\n" +
	"\x14SandboxUpdateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12:\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendTime\x88\x01\x01\x128\n" +
	"\x06egress\x18\x03 \x01(\v2\x1b.SandboxNetworkEgressConfigH\x01R\x06egress\x88\x01\x01B\v\n" +
	"\t_end_timeB\t\n" +
	"\a_egress\"5\n" +
	"\x14SandboxDeleteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"p\n" +
	"\x13SandboxPauseRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\"T\n" +
	"\x18SandboxCheckpointRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\"\x1b\n" +
	"\x19SandboxCheckpointResponse\"\xc7\x01\n" +
	"\x0eRunningSandbox\x12&\n" +
	"\x06config\x18\x01 \x01(\v2\x0e.SandboxConfigR\x06config\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"D\n" +
	"\x13SandboxListResponse\x12-\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x0f.RunningSandboxR\tsandboxes\"q\n" +
	"\x0fCachedBuildInfo\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12C\n" +
	"\x0fexpiration_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationTime\"K\n" +
	"\x1fSandboxListCachedBuildsResponse\x12(\n" +
	"\x06builds\x18\x01 \x03(\v2\x10.CachedBuildInfoR\x06builds2\xbb\x03\n" +
	"\x0eSandboxService\x127\n" +
	"\x06Create\x12\x15.SandboxCreateRequest\x1a\x16.SandboxCreateResponse\x127\n" +
	"\x06Update\x12\x15.SandboxUpdateRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x14.SandboxListResponse\x127\n" +
	"\x06Delete\x12\x15.SandboxDeleteRequest\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x05Pause\x12\x14.SandboxPauseRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"Checkpoint\x12\x19.SandboxCheckpointRequest\x1a\x1a.SandboxCheckpointResponse\x12L\n" +
	"\x10ListCachedBuilds\x12\x16.google.protobuf.Empty\x1a .SandboxListCachedBuildsResponseB+Z)github.com/cri-multiplex/pkg/orchestratorb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_orchestrator_proto_goTypes = []any{
	(*SandboxConfig)(nil),                   // 0: SandboxConfig
	(*SandboxAutoResumeConfig)(nil),         // 1: SandboxAutoResumeConfig
	(*SandboxVolumeMount)(nil),              // 2: SandboxVolumeMount
	(*SandboxNetworkConfig)(nil),            // 3: SandboxNetworkConfig
	(*SandboxNetworkTransform)(nil),         // 4: SandboxNetworkTransform
	(*SandboxNetworkRule)(nil),              // 5: SandboxNetworkRule
	(*SandboxNetworkDomainRules)(nil),       // 6: SandboxNetworkDomainRules
	(*SandboxNetworkEgressConfig)(nil),      // 7: SandboxNetworkEgressConfig
	(*SandboxNetworkIngressConfig)(nil),     // 8: SandboxNetworkIngressConfig
	(*SandboxCreateRequest)(nil),            // 9: SandboxCreateRequest
	(*SandboxCreateResponse)(nil),           // 10: SandboxCreateResponse
	(*SandboxUpdateRequest)(nil),            // 11: SandboxUpdateRequest
	(*SandboxDeleteRequest)(nil),            // 12: SandboxDeleteRequest
	(*SandboxPauseRequest)(nil),             // 13: SandboxPauseRequest
	(*SandboxCheckpointRequest)(nil),        // 14: SandboxCheckpointRequest
	(*SandboxCheckpointResponse)(nil),       // 15: SandboxCheckpointResponse
	(*RunningSandbox)(nil),                  // 16: RunningSandbox
	(*SandboxListResponse)(nil),             // 17: SandboxListResponse
	(*CachedBuildInfo)(nil),                 // 18: CachedBuildInfo
	(*SandboxListCachedBuildsResponse)(nil), // 19: SandboxListCachedBuildsResponse
	nil,                                     // 20: SandboxConfig.EnvVarsEntry
	nil,                                     // 21: SandboxConfig.MetadataEntry
	nil,                                     // 22: SandboxNetworkTransform.HeadersEntry
	nil,                                     // 23: SandboxNetworkEgressConfig.RulesEntry
	(*timestamp.Timestamp)(nil),             // 24: google.protobuf.Timestamp
	(*empty.Empty)(nil),                     // 25: google.protobuf.Empty
}
var file_orchestrator_proto_depIdxs = []int32{
	20, // 0: SandboxConfig.env_vars:type_name -> SandboxConfig.EnvVarsEntry
	21, // 1: SandboxConfig.metadata:type_name -> SandboxConfig.MetadataEntry
	3,  // 2: SandboxConfig.network:type_name -> SandboxNetworkConfig
	2,  // 3: SandboxConfig.volumeMounts:type_name -> SandboxVolumeMount
	1,  // 4: SandboxConfig.auto_resume:type_name -> SandboxAutoResumeConfig
	7,  // 5: SandboxNetworkConfig.egress:type_name -> SandboxNetworkEgressConfig
	8,  // 6: SandboxNetworkConfig.ingress:type_name -> SandboxNetworkIngressConfig
	22, // 7: SandboxNetworkTransform.headers:type_name -> SandboxNetworkTransform.HeadersEntry
	4,  // 8: SandboxNetworkRule.transform:type_name -> SandboxNetworkTransform
	5,  // 9: SandboxNetworkDomainRules.rules:type_name -> SandboxNetworkRule
	23, // 10: SandboxNetworkEgressConfig.rules:type_name -> SandboxNetworkEgressConfig.RulesEntry
	0,  // 11: SandboxCreateRequest.sandbox:type_name -> SandboxConfig
	24, // 12: SandboxCreateRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 13: SandboxCreateRequest.end_time:type_name -> google.protobuf.Timestamp
	24, // 14: SandboxUpdateRequest.end_time:type_name -> google.protobuf.Timestamp
	7,  // 15: SandboxUpdateRequest.egress:type_name -> SandboxNetworkEgressConfig
	0,  // 16: RunningSandbox.config:type_name -> SandboxConfig
	24, // 17: RunningSandbox.start_time:type_name -> google.protobuf.Timestamp
	24, // 18: RunningSandbox.end_time:type_name -> google.protobuf.Timestamp
	16, // 19: SandboxListResponse.sandboxes:type_name -> RunningSandbox
	24, // 20: CachedBuildInfo.expiration_time:type_name -> google.protobuf.Timestamp
	18, // 21: SandboxListCachedBuildsResponse.builds:type_name -> CachedBuildInfo
	6,  // 22: SandboxNetworkEgressConfig.RulesEntry.value:type_name -> SandboxNetworkDomainRules
	9,  // 23: SandboxService.Create:input_type -> SandboxCreateRequest
	11, // 24: SandboxService.Update:input_type -> SandboxUpdateRequest
	25, // 25: SandboxService.List:input_type -> google.protobuf.Empty
	12, // 26: SandboxService.Delete:input_type -> SandboxDeleteRequest
	13, // 27: SandboxService.Pause:input_type -> SandboxPauseRequest
	14, // 28: SandboxService.Checkpoint:input_type -> SandboxCheckpointRequest
	25, // 29: SandboxService.ListCachedBuilds:input_type -> google.protobuf.Empty
	10, // 30: SandboxService.Create:output_type -> SandboxCreateResponse
	25, // 31: SandboxService.Update:output_type -> google.protobuf.Empty
	17, // 32: SandboxService.List:output_type -> SandboxListResponse
	25, // 33: SandboxService.Delete:output_type -> google.protobuf.Empty
	25, // 34: SandboxService.Pause:output_type -> google.protobuf.Empty
	15, // 35: SandboxService.Checkpoint:output_type -> SandboxCheckpointResponse
	19, // 36: SandboxService.ListCachedBuilds:output_type -> SandboxListCachedBuildsResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	file_orchestrator_proto_msgTypes[0].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[3].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[5].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[8].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
